In [137]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


In [8]:
# Загрузка данных
data = load_iris()
X, y = data.data, data.target

# Разделение на тренировочную и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape

(120, 4)

In [ ]:
# Обучение и предсказание нескольких лесов
y_preds=[]#np.array([[]])
N=10
for i in range(N):
    rf = DecisionTreeClassifier(max_depth=10)
    # Создание бутстрэп выборки
    n_samples = int(X_train.shape[0]/3)
    idxs = np.random.choice(n_samples, n_samples, replace=True)
    X_bootstrap, y_bootstrap = X_train[idxs], y_train[idxs]
    rf.fit(X_bootstrap, y_bootstrap)
    y_pred = rf.predict(X_test)
    y_preds.append(y_pred.tolist())

#Сохраняем предсказание нескольких лесов
y_preds=np.array(y_preds)
print(y_preds)
y_preds.shape

[[1 0 2 1 2 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
 [1 0 2 1 2 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
 [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
 [1 0 2 1 2 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
 [1 0 2 1 2 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
 [1 0 2 1 2 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
 [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
 [1 0 2 1 2 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
 [1 0 2 1 2 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
 [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]]


(10, 30)

In [ ]:
# Голосуем за предсказание из нескольких лесов
from functools import reduce
y_pred=[]
for i in range(y_preds.shape[1]):
    max_number = reduce(lambda x, y: x if x > y else y, y_preds[:,i])
    y_pred.append(max_number)


In [ ]:
# Оценка точности
print("Точность:", accuracy_score(y_test, y_pred))
print("Полнота:", recall_score(y_test, y_pred, average=None))
print("F1-мера:", f1_score(y_test, y_pred, average=None))


Accuracy: 0.97
Точность: 0.9666666666666667
Полнота: [1.         0.88888889 1.        ]
F1-мера: [1.         0.94117647 0.95652174]


In [139]:
model_rf = RandomForestClassifier(n_estimators = 10, max_depth = 10)
model_rf.fit(X_train, y_train)
pred_rf = model_rf.predict(X_test)
# Оценка точности
print("Точность:", accuracy_score(y_test, pred_rf))
print("Полнота:", recall_score(y_test, pred_rf, average=None))
print("F1-мера:", f1_score(y_test, pred_rf, average=None))

Точность: 1.0
Полнота: [1. 1. 1.]
F1-мера: [1. 1. 1.]


Незнаю почему, но стандартный случайный лес работает немного лучше чем тот случайный лес который реализовал я.