In [1]:
import numpy as np
np.random.seed(1)
n=60
b=np.random.randint(1,7,n)
b

array([6, 4, 5, 1, 2, 4, 6, 1, 1, 2, 5, 6, 5, 2, 3, 5, 6, 3, 5, 4, 5, 3,
       5, 6, 3, 5, 2, 2, 1, 6, 2, 2, 6, 2, 2, 1, 5, 2, 1, 1, 6, 4, 3, 2,
       1, 4, 6, 2, 2, 4, 5, 1, 2, 4, 5, 3, 5, 1, 6, 4], dtype=int32)

In [2]:
a=b[b==3]
a

array([3, 3, 3, 3, 3, 3], dtype=int32)

W(A) - относительная частота события A,
m - число появления события A,
n - общее число испытаний.


In [3]:
m=len(a)
W=m/n
W

0.1

In [5]:
n=360
c=np.random.randint(1,7,n)
d=np.random.randint(1,7,n)
a=c[(c==1)&(d==2)]
a1=c[c==1]
a2=d[d==2]
a,a1,a2

(array([1, 1, 1, 1, 1, 1, 1], dtype=int32),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1], dtype=int32),
 array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2], dtype=int32))

In [6]:
m=len(a)
W=m/n
W

0.019444444444444445

Сколькими способами можно выбрать из колоды, состоящей из 36 карт, 4 карты? 

In [14]:
from math import factorial
def combination(n,k):
    return factorial(n)//(factorial(k)* factorial(n-k))

combination(36,4)

0.30523530523530523

В магазине 20 покупателей. Сколькими способами они могут образовать очередь из 5 человек?

In [25]:
def arran(n,k):
    return factorial(n)//factorial(n-k)

arran(20,5)

1860480

Сколькими способами 5 покупателей могут образовать очередь?

In [10]:
def perm(n):
    return factorial(n)

perm(5)

120