In [6]:
import numpy as np
import tensorflow as tf 


In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN

In [28]:
text='This is GeekBrains neural net arhitecture course!'
chars = sorted(list(set(text)))
char_to_index = {char: i for i, char in enumerate(chars) }
index_to_char = {i: char for i, char in enumerate(chars)}

In [31]:
len(chars)

18

In [18]:
seq_leght =4
sequence=[]
labels =[]
for i in range(0,len(text)-seq_leght):
    seq=text[i:i+seq_leght]
    label= text[i+seq_leght]
    sequence.append([char_to_index[char] for char in seq])
    labels.append(char_to_index[label])

In [32]:
sequence

[[4, 8, 9, 15],
 [8, 9, 15, 0],
 [9, 15, 0, 9],
 [15, 0, 9, 15],
 [0, 9, 15, 0],
 [9, 15, 0, 3],
 [15, 0, 3, 7],
 [0, 3, 7, 7],
 [3, 7, 7, 10],
 [7, 7, 10, 2],
 [7, 10, 2, 14],
 [10, 2, 14, 5],
 [2, 14, 5, 9],
 [14, 5, 9, 12],
 [5, 9, 12, 15],
 [9, 12, 15, 0],
 [12, 15, 0, 12],
 [15, 0, 12, 7],
 [0, 12, 7, 17],
 [12, 7, 17, 14],
 [7, 17, 14, 5],
 [17, 14, 5, 11],
 [14, 5, 11, 0],
 [5, 11, 0, 12],
 [11, 0, 12, 7],
 [0, 12, 7, 16],
 [12, 7, 16, 0],
 [7, 16, 0, 5],
 [16, 0, 5, 14],
 [0, 5, 14, 8],
 [5, 14, 8, 9],
 [14, 8, 9, 16],
 [8, 9, 16, 7],
 [9, 16, 7, 6],
 [16, 7, 6, 16],
 [7, 6, 16, 17],
 [6, 16, 17, 14],
 [16, 17, 14, 7],
 [17, 14, 7, 0],
 [14, 7, 0, 6],
 [7, 0, 6, 13],
 [0, 6, 13, 17],
 [6, 13, 17, 14],
 [13, 17, 14, 15],
 [17, 14, 15, 7]]

In [33]:
labels

[0,
 9,
 15,
 0,
 3,
 7,
 7,
 10,
 2,
 14,
 5,
 9,
 12,
 15,
 0,
 12,
 7,
 17,
 14,
 5,
 11,
 0,
 12,
 7,
 16,
 0,
 5,
 14,
 8,
 9,
 16,
 7,
 6,
 16,
 17,
 14,
 7,
 0,
 6,
 13,
 17,
 14,
 15,
 7,
 1]

In [19]:
X=np.array(sequence)
y=np.array(labels)

In [34]:
X

array([[ 4,  8,  9, 15],
       [ 8,  9, 15,  0],
       [ 9, 15,  0,  9],
       [15,  0,  9, 15],
       [ 0,  9, 15,  0],
       [ 9, 15,  0,  3],
       [15,  0,  3,  7],
       [ 0,  3,  7,  7],
       [ 3,  7,  7, 10],
       [ 7,  7, 10,  2],
       [ 7, 10,  2, 14],
       [10,  2, 14,  5],
       [ 2, 14,  5,  9],
       [14,  5,  9, 12],
       [ 5,  9, 12, 15],
       [ 9, 12, 15,  0],
       [12, 15,  0, 12],
       [15,  0, 12,  7],
       [ 0, 12,  7, 17],
       [12,  7, 17, 14],
       [ 7, 17, 14,  5],
       [17, 14,  5, 11],
       [14,  5, 11,  0],
       [ 5, 11,  0, 12],
       [11,  0, 12,  7],
       [ 0, 12,  7, 16],
       [12,  7, 16,  0],
       [ 7, 16,  0,  5],
       [16,  0,  5, 14],
       [ 0,  5, 14,  8],
       [ 5, 14,  8,  9],
       [14,  8,  9, 16],
       [ 8,  9, 16,  7],
       [ 9, 16,  7,  6],
       [16,  7,  6, 16],
       [ 7,  6, 16, 17],
       [ 6, 16, 17, 14],
       [16, 17, 14,  7],
       [17, 14,  7,  0],
       [14,  7,  0,  6],


In [36]:
y

array([ 0,  9, 15,  0,  3,  7,  7, 10,  2, 14,  5,  9, 12, 15,  0, 12,  7,
       17, 14,  5, 11,  0, 12,  7, 16,  0,  5, 14,  8,  9, 16,  7,  6, 16,
       17, 14,  7,  0,  6, 13, 17, 14, 15,  7,  1])

In [20]:
X_one_hot=tf.one_hot(X,len(chars))
y_one_hot=tf.one_hot(y,len(chars))

In [35]:
X_one_hot

<tf.Tensor: shape=(45, 4, 18), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0

In [37]:
y_one_hot

<tf.Tensor: shape=(45, 18), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 

In [21]:
model=Sequential()
model.add(SimpleRNN(50,input_shape=(seq_leght,len(chars)),activation='relu'))
model.add(Dense(len(chars),activation='softmax'))

c:\Users\rukavishnikovav\Python\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [22]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [23]:
model.fit(X_one_hot,y_one_hot,epochs=100)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.0000e+00 - loss: 2.9427
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.0252 - loss: 2.9095
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.0148 - loss: 2.8939    
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.0653 - loss: 2.8676
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.0801 - loss: 2.8533
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.0905 - loss: 2.8369
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.1201 - loss: 2.8164
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.1410 - loss: 2.7922
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.1706 - loss: 2.7773
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.2062 - loss: 2.7612
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.2167 - loss: 2.7295
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.2

In [41]:
start_seq='This is G'
gen_text=start_seq
for i in range(50):
    x=np.array([[char_to_index[char] for char in gen_text[-seq_leght:]]])
    print(x)
    x_one_hot= tf.one_hot(x,len(chars))
    predict=model.predict(x_one_hot)
    print(predict)
    next_index=np.argmax(predict)
    print(next_index)
    next_char=index_to_char[next_index]
    print(next_char)
    gen_text+=next_char
    print(gen_text)
print(gen_text)

[[ 9 15  0  3]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[[1.2739006e-04 6.8083039e-04 2.2200993e-04 1.9979263e-08 1.1352027e-07
  5.4229255e-04 5.0743279e-04 7.8192049e-01 1.1471880e-06 2.6056380e-06
  2.4538124e-06 4.8945953e-06 5.4397760e-03 2.6091144e-03 2.1521388e-04
  1.9728418e-01 1.0438504e-02 1.5136932e-06]]
7
e
This is Ge
[[15  0  3  7]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[[1.5208164e-01 6.6898684e-03 1.3838197e-03 1.3156434e-05 4.2670295e-06
  2.7621008e-05 8.9493937e-05 6.7002821e-01 3.3531200e-02 5.8783655e-05
  5.6390098e-04 3.4971901e-03 3.0329642e-05 5.2687747e-04 7.9056609e-04
  1.8781907e-04 4.9547188e-02 8.0948025e-02]]
7
e
This is Gee
[[0 3 7 7]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
[[1.0415779e-01 9.4558103e-03 7.4791643e-03 1.7365072e-02 1.2161485e-05
  1.3478873e-03 1.4488256e-01 1.0012417e-03 8.9557067e-04 1.3881819e-03
  6.4016742e-01 3.5769998e-03 6.9599965e-04 1.0023905e-05 6.4243391e-02
  4.8705176e-04 2.3118306e-04 2.6024729e-03]]
10
k
This is Geek
[[ 3  7