In [5]:
import torch
tensor = torch.tensor([1, 2, 3]) # Одномерный тензор (вектор)
print(tensor.shape) # Вывод: torch.Size([3])

#Для многомерных тензоров форма описывает размерность по каждой оси:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]]) # Матрица (двумерный тензор)
print(tensor.shape) # Вывод: torch.Size([2, 3])

#В PyTorch форма (shape) и размер (size) означают одно и то же.
print(tensor.size())
# Вывод: torch.Size([2, 3])
#Переформатирование тензоров позволяет изменять их форму, не изменяя данные:
reshaped_tensor = tensor.reshape(3, 2)
# Изменяем форму с (2, 3) на (3, 2)
print(reshaped_tensor.shape)
print(reshaped_tensor)

torch.Size([3])
torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([3, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [6]:
import torch
import numpy as np
# Создание пустого тензора
t = torch.Tensor()
print(type(t)) # Вывод: torch.Tensor
#PyTorch предоставляет важные атрибуты для анализа тензоров:
print(t.dtype) # Тип данных в тензоре (например, float32).
print(t.device) # Устройство, на котором размещён тензор (CPU или GPU).
print(t.layout) # Указывает расположение данных в памяти.
#Пример:
a = torch.Tensor([2, 2]) # Создание тензора
print(a.dtype) # Вывод: torch.float32
print(a.device) # Вывод: cpu


<class 'torch.Tensor'>
torch.float32
cpu
torch.strided
torch.float32
cpu


Создание тензоров из данных

In [10]:
import torch
import numpy as np
data = np.array([1, 2, 3])
# 1. С помощью factory-функции `torch.tensor`
a = torch.tensor(data)
print('tensor:', a)
# 2. С помощью конструктора класса `torch.Tensor` (возвращает float)
b = torch.Tensor(data)
print('Tensor:', b)
# 3. С помощью функции `torch.as_tensor`
c = torch.as_tensor(data)
print('torch.as_tensor:', c)
# 4. С помощью функции `torch.from_numpy`
d = torch.from_numpy(data)
17
print('torch.from_numpy:', d)


tensor: tensor([1, 2, 3], dtype=torch.int32)
Tensor: tensor([1., 2., 3.])
torch.as_tensor: tensor([1, 2, 3], dtype=torch.int32)
torch.from_numpy: tensor([1, 2, 3], dtype=torch.int32)


Создание пустых тензоров (без исходных данных)

In [12]:
# Единичная матрица
a = torch.eye(3)
print('eye:', a)
# Матрица из нулей
b = torch.zeros(2, 2)
print('zeros:', b)
# Матрица из единиц
c = torch.ones(2, 2)
print('ones:', c)
# Матрица случайных чисел
d = torch.rand(2, 2)
print('Матрица случайных чисел:', d)

eye: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
zeros: tensor([[0., 0.],
        [0., 0.]])
ones: tensor([[1., 1.],
        [1., 1.]])
Матрица случайных чисел: tensor([[0.9386, 0.8625],
        [0.3447, 0.3362]])


Операции с тензорами

In [13]:
t = torch.tensor([
[1, 2, 3, 3],
[2, 2, 2, 2],
[3, 3, 3, 3]
], dtype=torch.float32)
print(t.size()) # torch.Size([3, 4])
print(t.numel()) # 12
# Примеры reshape
print(t.reshape(1, 12)) # [[1., 2., ...]]
print(t.reshape(6, 2)) # [[1., 2.], [3., 3.], ...]
print(t.reshape(2, 2, 3)) # 3-мерный тензор
#Метод .squeeze() удаляет оси размерности 1, например, из [1, 12] делает [12].
t = t.reshape(1, 12)
print(t.squeeze()) # [1., 2., 3., ...]
#Поэлементные операции выполняются между соответствующими элементами тензоров одинаковой формы.
t1 = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
t2 = torch.tensor([[9, 8], [7, 6]], dtype=torch.float32)
print(t1 + t2) # Сложение
print(t1 - t2) # Вычитание
print(t1 * t2) # Умножение
#Broadcasting позволяет проводить операции между тензорами разного размера,автоматически расширяя их до совместимой формы.
t1 = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print(t1 + 2) # [[3., 4.], [5., 6.]] (2 "расширяется" до [[2, 2], [2, 2]])
t2 = torch.tensor([2, 4], dtype=torch.float32)
print(t1 + t2) # [[3., 6.], [5., 8.]]
#Сравнения возвращают булевый тензор, где каждый элемент — результат операции.
t = torch.tensor([
[0, 5, 0],
[6, 0, 7],
[0, 8, 0]
], dtype=torch.float32)
print(t.eq(0)) # Равно 0
print(t.gt(5)) # Больше 5
print(t.le(7)) # Меньше или равно 7
#PyTorch поддерживает такие операции, как модуль числа, квадратный корень, отрицание.
print(t.abs()) # Модуль
print(t.sqrt()) # Квадратный корень
print(t.neg()) # Отрицание
#Объединение тензоров Конкатенация — метод .cat() объединяет тензоры вдоль указанной оси.
t1 = torch.tensor([[1, 2], [1, 2]])
t2 = torch.tensor([[3, 4], [3, 4]])
print(torch.cat((t1, t2), dim=1)) # Объединение по оси 1
#Стекирование — метод .stack() создаёт дополнительное измерение.
t1 = torch.tensor([[1, 1], [1, 1]])
t2 = torch.tensor([[2, 2], [2, 2]])
t3 = torch.tensor([[3, 3], [3, 3]])
t = torch.stack((t1, t2, t3))
print(t.size()) # torch.Size([3, 2, 2])
#Индексация позволяет извлекать данные по определённым координатам.
t = torch.tensor([
[[1, 1], [2, 2]],
[[3, 3], [4, 4]],
[[5, 5], [6, 6]]
])
print(t[0]) # Первый «батч»
print(t[0][0]) # Первый канал
print(t[0][0][0]) # Первый элемент
20
#«Разворачивание» тензоров (Flatten) Метод .flatten() превращает тензор в одномерный.
print(t.flatten()) # Все элементы в одном измерении
print(t.flatten(start_dim=1)) # «Разворачивание» по осям, начиная с оси 1

torch.Size([3, 4])
12
tensor([[1., 2., 3., 3., 2., 2., 2., 2., 3., 3., 3., 3.]])
tensor([[1., 2.],
        [3., 3.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])
tensor([[[1., 2., 3.],
         [3., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])
tensor([1., 2., 3., 3., 2., 2., 2., 2., 3., 3., 3., 3.])
tensor([[10., 10.],
        [10., 10.]])
tensor([[-8., -6.],
        [-4., -2.]])
tensor([[ 9., 16.],
        [21., 24.]])
tensor([[3., 4.],
        [5., 6.]])
tensor([[3., 6.],
        [5., 8.]])
tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])
tensor([[False, False, False],
        [ True, False,  True],
        [False,  True, False]])
tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])
tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])
tensor([[0.0000, 2.2361, 0.0000],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])
tensor([